apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-openidm-postgres-openidm
    release: postgres-openidm
  name: postgres-openidm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
