# WARNING: Base image reference should not be set manually.
# To "upgrade" to a later release of the Identity Stack, use the script: /scripts/upgrade_identity_stack.sh
FROM gcr.io/forgerock-io/idm/pit1:7.0.0-4da29dc
COPY conf /opt/openidm/conf
COPY script /opt/openidm/script
