#!/usr/bin/env sh
# This script copies the config from the am-config container filesystem to the openam-root mounted volume
# so that it can be read by the main openam container within the Kubernetes pod

set -x

echo "Copying config"
mkdir -p /home/forgerock/openam/config
cp -R /home/forgerock/config/* /home/forgerock/openam/config

## org.forgerock.openam.utils.AMKeyProvider#readPasswordFile logs errors:
## Unable to read private key password file /home/forgerock/openam/am/.storepass
## Unable to read private key password file /home/forgerock/openam/am/.keypass
## (stacktrace at end of script)
echo "Copying default passwords"
mkdir -p /home/forgerock/openam/am
cp /home/forgerock/openam/security/secrets/default/.storepass /home/forgerock/openam/am/.storepass
cp /home/forgerock/openam/security/secrets/default/.keypass /home/forgerock/openam/am/.keypass

#echo "Copying keystore.jceks"
#mkdir -p /home/forgerock/openam/security/keystores
#rm -f /home/forgerock/openam/security/keystores/keystore.jceks
#cp /home/forgerock/keystore.jceks /home/forgerock/openam/security/keystores

# Unable to read private key password file /home/forgerock/openam/am/.storepass
#  exception: "java.io.FileNotFoundException: /home/forgerock/openam/am/.storepass (No such file or directory)
#	at java.base/java.io.FileInputStream.open0(Native Method)
#	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
#	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
#	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
#	at java.base/java.io.FileReader.<init>(FileReader.java:60)
#	at org.forgerock.openam.utils.AMKeyProvider.readPasswordFile(AMKeyProvider.java:188)
#	at org.forgerock.openam.utils.AMKeyProvider.initialize(AMKeyProvider.java:168)
#	at org.forgerock.openam.utils.AMKeyProvider.<init>(AMKeyProvider.java:123)
#	at org.forgerock.openam.utils.AMKeyProvider.<init>(AMKeyProvider.java:91)
#	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
#	at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:126)
#	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
#	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
#	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
#	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
#	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
#	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
#	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
#	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
#	at org.forgerock.guice.core.InjectorHolder.getInstance(InjectorHolder.java:72)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer$EncryptionAlgorithm.getAmEncryption(SmsPasswordTransformer.java:80)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer$EncryptionAlgorithm.access$100(SmsPasswordTransformer.java:52)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer.isEncryptionSupported(SmsPasswordTransformer.java:120)
#	at org.forgerock.openam.core.sms.SmsJsonConverter.fromJson(SmsJsonConverter.java:458)
#	at org.forgerock.openam.sm.file.converter.ConfigEntityConverter.toLdapValueAttributes(ConfigEntityConverter.java:169)
#	at org.forgerock.openam.sm.file.converter.ConfigEntityConverter.convertToLdapAttributes(ConfigEntityConverter.java:99)
#	at org.forgerock.openam.sm.FileBasedSmsObject.readFileData(FileBasedSmsObject.java:189)
#	at org.forgerock.openam.sm.FileBasedSmsObject.read(FileBasedSmsObject.java:171)
#	at com.sun.identity.sm.SmsWrapperObject.read(SmsWrapperObject.java:143)
#	at com.sun.identity.sm.SMSEntry.read(SMSEntry.java:603)
#	at com.sun.identity.sm.SMSEntry.read(SMSEntry.java:595)
#	at com.sun.identity.sm.SMSEntry.<init>(SMSEntry.java:359)
#	at com.sun.identity.sm.CachedSMSEntry.getInstance(CachedSMSEntry.java:359)
#	at com.sun.identity.sm.ServiceConfigImpl.checkAndUpdatePermission(ServiceConfigImpl.java:713)
#	at com.sun.identity.sm.ServiceConfigImpl.getInstance(ServiceConfigImpl.java:604)
#	at com.sun.identity.sm.ServiceConfigImpl.getSubConfig(ServiceConfigImpl.java:264)
#	at com.sun.identity.sm.ServiceConfig.getSubConfig(ServiceConfig.java:298)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.initialisePrometheusConfig(MonitoringManager.java:282)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.loadMonitoringService(MonitoringManager.java:181)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.setupMonitoringService(MonitoringManager.java:154)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.setupComplete(MonitoringManager.java:133)
#	at org.forgerock.openam.monitoring.configuration.MonitoringSetupListener.setupComplete(MonitoringSetupListener.java:21)
#	at com.sun.identity.setup.AMSetupServlet.notifyAmStartup(AMSetupServlet.java:1849)
#	at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:236)
#	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
#	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
#	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
#	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4871)
#	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5180)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
#	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
#	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
#	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
#	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867)
#	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
#	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
#	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
#	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
#	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
#	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
#	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
#	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
#	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
#	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
#	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
#	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
#	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
#	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
#	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
#	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
#	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
#	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
#	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)

# Unable to read private key password file /home/forgerock/openam/am/.keypass
#exception: "java.io.FileNotFoundException: /home/forgerock/openam/am/.keypass (No such file or directory)
#	at java.base/java.io.FileInputStream.open0(Native Method)
#	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
#	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
#	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
#	at java.base/java.io.FileReader.<init>(FileReader.java:60)
#	at org.forgerock.openam.utils.AMKeyProvider.readPasswordFile(AMKeyProvider.java:188)
#	at org.forgerock.openam.utils.AMKeyProvider.initialize(AMKeyProvider.java:176)
#	at org.forgerock.openam.utils.AMKeyProvider.<init>(AMKeyProvider.java:123)
#	at org.forgerock.openam.utils.AMKeyProvider.<init>(AMKeyProvider.java:91)
#	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
#	at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:126)
#	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
#	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
#	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
#	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
#	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
#	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
#	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
#	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
#	at org.forgerock.guice.core.InjectorHolder.getInstance(InjectorHolder.java:72)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer$EncryptionAlgorithm.getAmEncryption(SmsPasswordTransformer.java:80)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer$EncryptionAlgorithm.access$100(SmsPasswordTransformer.java:52)
#	at org.forgerock.openam.core.sms.SmsPasswordTransformer.isEncryptionSupported(SmsPasswordTransformer.java:120)
#	at org.forgerock.openam.core.sms.SmsJsonConverter.fromJson(SmsJsonConverter.java:458)
#	at org.forgerock.openam.sm.file.converter.ConfigEntityConverter.toLdapValueAttributes(ConfigEntityConverter.java:169)
#	at org.forgerock.openam.sm.file.converter.ConfigEntityConverter.convertToLdapAttributes(ConfigEntityConverter.java:99)
#	at org.forgerock.openam.sm.FileBasedSmsObject.readFileData(FileBasedSmsObject.java:189)
#	at org.forgerock.openam.sm.FileBasedSmsObject.read(FileBasedSmsObject.java:171)
#	at com.sun.identity.sm.SmsWrapperObject.read(SmsWrapperObject.java:143)
#	at com.sun.identity.sm.SMSEntry.read(SMSEntry.java:603)
#	at com.sun.identity.sm.SMSEntry.read(SMSEntry.java:595)
#	at com.sun.identity.sm.SMSEntry.<init>(SMSEntry.java:359)
#	at com.sun.identity.sm.CachedSMSEntry.getInstance(CachedSMSEntry.java:359)
#	at com.sun.identity.sm.ServiceConfigImpl.checkAndUpdatePermission(ServiceConfigImpl.java:713)
#	at com.sun.identity.sm.ServiceConfigImpl.getInstance(ServiceConfigImpl.java:604)
#	at com.sun.identity.sm.ServiceConfigImpl.getSubConfig(ServiceConfigImpl.java:264)
#	at com.sun.identity.sm.ServiceConfig.getSubConfig(ServiceConfig.java:298)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.initialisePrometheusConfig(MonitoringManager.java:282)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.loadMonitoringService(MonitoringManager.java:181)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.setupMonitoringService(MonitoringManager.java:154)
#	at org.forgerock.openam.monitoring.configuration.MonitoringManager.setupComplete(MonitoringManager.java:133)
#	at org.forgerock.openam.monitoring.configuration.MonitoringSetupListener.setupComplete(MonitoringSetupListener.java:21)
#	at com.sun.identity.setup.AMSetupServlet.notifyAmStartup(AMSetupServlet.java:1849)
#	at com.sun.identity.setup.AMSetupServlet.init(AMSetupServlet.java:236)
#	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
#	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
#	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
#	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4871)
#	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5180)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
#	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
#	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
#	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
#	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867)
#	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
#	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
#	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
#	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
#	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
#	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
#	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
#	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
#	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
#	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
#	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
#	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
#	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
#	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
#	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
#	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
#	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
#	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
#	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
#	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
#	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)