apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: gcr.io/engineering-devops/sk-amster
# See https://github.com/GoogleContainerTools/skaffold/issues/360
deploy:
  helm:
    releases:
    - name: sk-amster
      chartPath: ../helm/amster  
      imageStrategy:
        helm: {}
      values:
        image: gcr.io/engineering-devops/sk-amster
      # Current skaffold bug - needs to have a values path
      valuesFilePath: skaffold-values.yaml
      setValues:
        skaffold: "true"
        config.strategy: "docker"
        config.importPath: "/git"
        domain: ".example.com"
  