apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/skaffold/idm-am-common-user/amster
    context: ../amster
  - image: gcr.io/engineering-devops/skaffold/idm-am-common-user/idm
    context: ../idm
  tagPolicy:
    sha256: {}
  local:
    push: false
deploy:
  helm:
    releases:
    - name: sk-frconfig
      chartPath: helm/frconfig
      setValues:
        domain: .forgeops.com
        certmanager.acme: false
        certmanager.issuer: ca-issuer
        certmanager.issuerKind: Issuer

    - name: sk-amster
      chartPath: helm/amster
      valuesFiles:
      - amster-values.yaml
      values:
        image: gcr.io/engineering-devops/skaffold/idm-am-common-user/amster
      imageStrategy:
        helm: {}

    - name: sk-idm
      chartPath: helm/openidm
      valuesFiles:
      - idm-values.yaml
      values:
        image: gcr.io/engineering-devops/skaffold/idm-am-common-user/idm
      imageStrategy:
        helm: {}

    - name: sk-openam
      chartPath: helm/openam
      valuesFiles:
      - openam-values.yaml

    - name: sk-configstore
      chartPath: helm/ds
      valuesFiles:
      - configstore-values.yaml
