apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: ds-ds
    component: ds
    instance: userstore
    release: ds
    vendor: forgerock
  name: userstore
spec:
  replicas: 1
  serviceName: userstore
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: ds-ds
        component: ds
        instance: userstore
        release: ds
        vendor: forgerock
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: instance
                  operator: In
                  values:
                  - userstore
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - start
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: userstore
        image: forgerock-docker-public.bintray.io/forgerock/ds:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 120
          tcpSocket:
            port: metrics
        name: ds
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 4444
          name: admin
        - containerPort: 8989
          name: replication
        - containerPort: 8080
          name: metrics
        resources:
          limits:
            memory: 768Mi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/run/secrets/opendj
          name: dj-secrets
        - mountPath: /opt/opendj/bak
          name: backup
        - mountPath: /opt/opendj/logs
          name: logs
        - mountPath: /opt/opendj/data
          name: db
      securityContext:
        fsGroup: 11111
        runAsUser: 11111
        supplementalGroups:
        - 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dj-secrets
        secret:
          secretName: userstore
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: backup
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations:
        pv.beta.kubernetes.io/gid: "11111"
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
