  domain: .forgeops.com
  service:
    name: idm-service
    externalPort: 8080
  resources:
    requests:
      memory: "512Mi"
  config:
    strategy: files
    path: /opt/openidm
  ingress:
    enabled: false
