apiVersion: v1
data:
  id_rsa: VGhpcyBpcyBhIGR1bW15IHNlY3JldCBmb3IgZ2l0IHNzaCBhY2Nlc3MuIElmIHlvdSBhcmUgdXNpbmcgYSBwcml2YXRlIGdpdCByZXBvCnRoYXQgcmVxdWlyZXMgYW4gc3NoIGtleSwgcmVwbGFjZSB0aGlzIGZpbGUgd2l0aCB5b3VyIGdlbmVyYXRlZCBpZF9yc2Ega2V5LApTZWUgdGhlIFJFQURNRS4K
kind: Secret
metadata:
  name: frconfig
type: Opaque
