apiVersion: v1
kind: Pod
metadata:
  name: idm
  namespace: alex
  labels:
    role: management
spec:
  initContainers:
  - name: wait-for-repo
    image: "forgerock-docker-public.bintray.io/forgerock/util:6.0.0"
    imagePullPolicy: Always
    args: [ "wait", "ds-0.ds", "1389" ]
  containers:
    - image: gcr.io/engineering-devops/openidm:alextest
      imagePullPolicy: Always
      name: openidm
      env:
      - name: IDM_ENVCONFIG_DIRS
        value: /opt/openidm/resolver
      - name: OPENIDM_CLUSTER_REMOVE_OFFLINE_NODE_STATE
        value: "true"
      - name: OPENIDM_CONFIG_REPO_ENABLED
        value: "false"
      - name: OPENIDM_ANONYMOUS_PASSWORD
        value: "anonymous"
      - name: OPENIDM_ADMIN_PASSWORD
        value: "openidm-admin"
      ports:
        - containerPort: 8080
          name: mutualssl
          protocol: TCP
      resources:
          requests:
            memory: "512Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: idm-service
  namespace: alex
spec:
  ports:
    - port: 8080
      name: mutualssl
      targetPort: 8080
  selector:
    role: management
